### ISSUE TITLE
No resource or method named `apt_repository' 

### ISSUE THREAD

**Issue by chuangtim** [sous-chefs/mongodb-cookbook#107]
Hi
I got an errors when vagrant up ,an error as following:

``` ruby
No resource or method named `apt_repository' for `Chef::Recipe "mongodb_org_repo"'

==> db: Cookbook Trace:
==> db: ---------------
==> db:   /tmp/vagrant-chef/9a8c53e11c04eec3d9bc4a4b4c58fe0a/cookbooks/mongodb/recipes/mongodb_org_repo.rb:29:in `from_file'
==> db:   /tmp/vagrant-chef/9a8c53e11c04eec3d9bc4a4b4c58fe0a/cookbooks/mongodb/recipes/10gen_repo.rb:2:in `from_file'
==> db:   /tmp/vagrant-chef/9a8c53e11c04eec3d9bc4a4b4c58fe0a/cookbooks/mongodb/recipes/install.rb:2:in `from_file'
==> db:   /tmp/vagrant-chef/9a8c53e11c04eec3d9bc4a4b4c58fe0a/cookbooks/mongodb/recipes/default.rb:22:in `from_file'
==> db:   /tmp/vagrant-chef/9a8c53e11c04eec3d9bc4a4b4c58fe0a/cookbooks/cookbook-test/recipes/mongodb.rb:2:in `from_file'
==> db:
==> db:
==> db: Relevant File Content:
==> db: ----------------------
==> db: /tmp/vagrant-chef/9a8c53e11c04eec3d9bc4a4b4c58fe0a/cookbooks/mongodb/recipes/mongodb_org_repo.rb:
==> db:
==> db:  22:  # Sets up the repositories for stable mongodb-org packages found here:
==> db:  23:  # http://www.mongodb.org/downloads#packages
==> db:  24:  node.override['mongodb']['package_name'] = 'mongodb-org'
==> db:  25:
==> db:  26:  case node['platform_family']
==> db:  27:  when 'debian'
==> db:  28:    # Adds the repo: http://www.mongodb.org/display/DOCS/Ubuntu+and+Debian+packages
==> db:  29>>   apt_repository 'mongodb' do
==> db:  30:      uri "#{node[:mongodb][:repo]}/#{node[:mongodb][:apt_repo]}"
==> db:  31:      distribution 'dist'
==> db:  32:      components ['10gen']
==> db:  33:      keyserver 'hkp://keyserver.ubuntu.com:80'
==> db:  34:      key 'EA312927'
==> db:  35:      action :add
==> db:  36:    end
==> db:  37:
==> db:  38:  when 'rhel', 'fedora'
```

I can`t found apt-repository resource  referencing chef resource, which confused me.

**Comment by dpattmann** [comment]
Hi @chuangtim, the ```apt_repository``` resource comes from the [apt cookbook](https://github.com/chef-cookbooks/apt). You have to include the apt cookbook if you want to use this cookbook.

**Comment by shortdudey123** [comment]
Closing since `apt_repository` is now in chef core and the cookbook is no longer needed w/ chef 12.15+
For < 12.15, the apt cookbook is listed under `depends` in the metadata, so berkshelf should pick it up
